### ISSUE TITLE
Index for large Bed files

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#133]
For large Bed files, IGV suggests creating an optional index file to optimize track rendering. Seems it is a good idea and we could support indexes too.

**Comment by receed** [comment]
Assuming that the most useful kind of index is such that allows to traverse only entries on query chromosome, should we support indexes for Bed files where entries are not grouped by chromosome?
I see two options in this case:
- group the entries by chromosome and store them in the index, so that index size is close to original file size
- store locations of features on genome and their positions in Bed file, but then reading the entries would lead to many random disk reads.

For files with grouped entries it is enough to save positions where entries for a new chromosome start, it would yield small index size and fast sequential reads.

**Comment by olegs** [comment]
I'd say that almost all (95%+) of BED tracks are grouped by chromosome, with vast majority of them also sorted by positions.
However there can be exceptions.

**Comment by receed** [comment]
`htsjdk` library contains an implementation of indexes for large BED files (JBR already has a dependency on this library). Would it be better to use that index (with some additional code to convert data types) or to re-implement it?

**Comment by olegs** [comment]
Good catch! Of course it would be better to reuse existing implementation it it meets all the requirements.

**Comment by olegs** [comment]
Obsolete, already implemented
