### ISSUE TITLE
Cursor lines stay after cursor is disabled

### ISSUE THREAD

**Issue by Xewar313** [JetBrains-Research/jbr#222]
The dashed lines created by cursor when it is enabled do no disappear when cursor is disabled using menu
![image](https://github.com/JetBrains-Research/jbr/assets/69756491/ced5fdac-3ccf-45a6-9a8d-e0d01605689f)

**Comment by iromeo** [comment]
Initially, it was a feature, like clear by "ESC" and disable/enable by the separate shortcut. But then it was updated to changed shortcuts and current inconsistent behaviour appeared.

I like the idea to allow keeping so I can use it like vertical marker. 
* E.g. it will not be occasionally changed when scrolling tracks in large section, if I interested in a certain genome offset and all information at the offset. Or  to mark position in BAM coverage on a certain nucleotide and than scroll through 2000px size BAM track to see how all reads behave at the marked offset
* Could be used as some vertical marker / bound, when we scroll horizontally and want to align some track information according to it

At the moment freeze feature is not supported and it is easy to occasionally move the maker when you don't want. Also, due to  implemented information at mouse pointer, we could review cursor feature and maybe remove genomic position or replace it with distance in pixels.

**Comment by iromeo** [comment]
Fixed. The ability to freeze the cursor wasn't implemented. It is possible to use keyboard navigation for scrolling. Not sure how to make freeze option easy to use and easy to guess/find
