### ISSUE TITLE
ENCODE project search: multiline text is not shown

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#90]
See screenshot
<img width="798" alt="Screenshot 2020-01-14 at 16 05 02" src="https://user-images.githubusercontent.com/75644/72346758-a150e500-36e7-11ea-878b-1aeaf1844fbb.png">

**Comment by olegs** [comment]
Still here. Probably it has nothing to do with multiline, but some text is being cutted by the line height.

<img width="791" alt="Screenshot 2020-01-23 at 17 59 08" src="https://user-images.githubusercontent.com/75644/72995491-14560c00-3e0a-11ea-965c-8c0ca4ddeb96.png">

**Comment by dievsky** [comment]
Wow, weird. That's how the same output looks to me:
![jbr-encode-240120](https://user-images.githubusercontent.com/1926074/73060763-dc49da00-3e98-11ea-9c0b-92e6823fb53b.png)

I'll try to get to the bottom of this.

Note to future readers: the experiment description here is actually a single line (the string contains no newline characters), but this very long string is wrapped by the JTextArea. The difficulty is in resizing the JTextArea and its parent JPanel to the necessary height and in making the JTree respect that height. At least one step of the three is likely broken for @olegs on MacOS, while all of them work for me on Linux.

**Comment by dievsky** [comment]
A general note: JBR uses the default Java look-and-feel for all OSes _except_ MacOS X. For MacOS X, the system look-and-feel is used. The difference is likely to be caused by this.

In that case, the simplest (if not the most elegant) solution would be to force the Java look-and-feel for this particular JTree and its parts.

**Comment by dievsky** [comment]
@olegs could you please try again with the latest version? If that doesn't fix things, I'll have to get a Mac (or at least a MacOS VM) to test it live.

**Comment by olegs** [comment]
Just checked, unfortunately it didn't help. You'd better get a computer with Mac OS to reproduce.

**Comment by dievsky** [comment]
That's the plan.

**Comment by dievsky** [comment]
A couple of grey hairs later, I've identified the culprit: https://youtrack.jetbrains.com/issue/KT-36205 .

In short, when you access a `protected` Java field as a property, it bypasses the setter / getter methods, which is absolutely disastrous for Swing framework, since setters fire the "property changed" events and generally update the component state. The exact same approach works seamlessly for `private` fields, so you just have to check the field visibility before accessing it.

**Comment by olegs** [comment]
WIth Oracle JDK 11 I get the following issue:
<img width="796" alt="Screenshot 2020-01-28 at 18 39 56" src="https://user-images.githubusercontent.com/75644/73279156-bce6e000-41fd-11ea-9d2a-156e781e047d.png">

**Comment by dievsky** [comment]
Progress notes:
- the issue reproduces on macOS + OpenJDK 11;
- the current code didn't compile on Ubuntu + OpenJDK 11, see #94 ;
- after some tweaking I got the code to run on Ubuntu + OpenJDK 11, but the issue wasn't reproduced.

So the difference likely lies in the OS (and probably corresponding JDK distributions). For some currently unidentified reason, the JTextArea holding the description claims preferred height of 390 px on macOS.

**Comment by dievsky** [comment]
I ended up just setting the preferred size of the area explicitly. It sure seems easier than waddling through all the places at which it might have got corrupted.

With recent changes, I get the same (desired) results on both Ubuntu / macOS and both OpenJDK 8 / 11.

@olegs could you please check once again whether it works for you?

**Comment by olegs** [comment]
Finally, working, closing the issue.
