### ISSUE TITLE
ENCODE search: filtering by file format and add group as tracks

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/jbr#99]
Let's try the usecase:
*  find all CD14 tracks and open narrowPeaks in browser. 
*  find all CD14 tracks and open *.bigWig for histone modifications in browser. 
![image](https://user-images.githubusercontent.com/72933/74672844-259ef800-51bf-11ea-9510-b3ea91ebf056.png)

Both usecase requires too manually expand each `group`, select required files from all *.bed files there. Could we make it more convenient? 

E.g. we could add other file types to the bottom line. Also If group node is selected `Add Track(s)` button is disabled at the moment. I expect, that it will add all suitable files from the group.

![image](https://user-images.githubusercontent.com/72933/74673400-297f4a00-51c0-11ea-933d-22b425177a5a.png)

**Comment by dievsky** [comment]
Since we switched to table view, the ability to add a dataset is no longer relevant (since there's no more dataset nodes).
The `narrowPeak` use case is currently solved like this:
1. search for `CD14`,
2. right-click on `file type` to bring up the filter menu, ctrl-click on `narrowPeak` to select that type only;
3. do the same for `file format` and `bed`,

**Comment by olegs** [comment]
Closing as obsolete.
